In [1]:
# %pip install ..

In [2]:
from pyTrajectory.data_structures import InstanceCollection, Trajectory, TimestampedInstanceCollection
import numpy as np

In [3]:
cfg = Trajectory().cfg

In [95]:
cfg.trajectory_keys = ("position", "time", "identity")
cfg.key_timestamp = "time"
cfg.key_identity = "identity"

data = {
    "position": np.array([[0, 0], [1, 1], [2, 2], [3, 3]]),
    "time": np.array([0, 0, 1, 1]),
    "identity": np.array(["1", "1", "2", "2"], dtype=np.dtypes.StringDType),
}
collection = TimestampedInstanceCollection(data=data, cfg=cfg)

In [96]:
subcollection = collection[:2]

In [97]:
subcollection["identity"] = "new_name"

In [98]:
collection["identity"]

array(['new_name', 'new_name', '2', '2'], dtype=StringDType())

In [99]:
collection["identity"] = np.array(["hans", "hans","peter", "peter"])
collection[-1, "time"] = 5

In [100]:
from pyTrajectory import math

In [101]:
from pyTrajectory.features import keypoints

In [105]:
collection["position"]

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3]])

In [112]:
perform_operation(
    math.euclidean_distance,
    collection["position"][:, np.newaxis],
    collection["position"][:-2][np.newaxis, ...],
    element_wise=False,
    flat=False,
    expand_dims_for_broadcasting=False,
)

array([[0.        , 1.41421356],
       [1.41421356, 0.        ],
       [2.82842712, 1.41421356],
       [4.24264069, 2.82842712]])

In [93]:
collection["position"][:, np.newaxis].shape

(4, 1, 1, 2)

In [10]:
cfg() == cfg.copy()()

True

In [11]:
cfg = Trajectory().cfg

In [12]:
cfg.trajectory_keys = ("position", "time")
cfg.key_timestamp = "time"

data = {
    "position": np.array([[0, 0], [1, 1], [2, 2]]),
    "time": np.array([0, 1, 2]),
}
trajectory = Trajectory(data=data, cfg=cfg)


trajectory["position"], trajectory["time"]


(array([[0, 0],
        [1, 1],
        [2, 2]]),
 array([0, 1, 2]))

In [13]:
trajectory.keys()

('time', 'position')

In [14]:
trajectory.values()

(array([0, 1, 2]),
 array([[0, 0],
        [1, 1],
        [2, 2]]))

In [15]:
trajectory.items()

(('time', array([0, 1, 2])),
 ('position', array([[0, 0],
         [1, 1],
         [2, 2]])))

In [16]:
trajectory.length, len(trajectory)

(3, 3)

In [17]:
data = {"location": np.array([[0, 0], [1, 1], [2, 2]]), "time": np.array([1, 2, 3])}
# trajectory.validate_data(data)

In [18]:
data = {"position": np.array([[0, 0], [1, 1]]), "time": np.array([1, 2, 3])}
# trajectory.validate_data(data)

In [19]:
trajectory.data

{'time': array([0, 1, 2]),
 'position': array([[0, 0],
        [1, 1],
        [2, 2]])}

In [20]:
data = {
    "position": np.array([[1, 1], [2, 2], [4, 4]]),
    "time": np.array([1, 2, 4]),
}
trajectory = Trajectory(data=data)

In [21]:
# trajectory["position"] += 1

In [22]:
trajectory[("position", "time")]

(array([[1, 1],
        [2, 2],
        [4, 4]]),
 array([1, 2, 4]))

In [23]:
trajectory[:2].data

{'time': array([1, 2]),
 'position': array([[1, 1],
        [2, 2]])}

In [24]:
trajectory[1:2, "position"]

array([[2, 2]])

In [25]:
trajectory[1:3, ["position", "time"]]

{'position': array([[2, 2],
        [4, 4]]),
 'time': array([2, 4])}

In [26]:
trajectory["time"].dtype

dtype('int64')

In [27]:
trajectory.sample(timestamps=[1.005]).data

{'time': array([1.005]), 'position': array([[1.005, 1.005]])}

In [28]:
data = {
    "position": np.array([[1, 1], [2, 2], [4, 4]]).astype(float),
    "time": np.array([1, 2, 4], dtype=float),
}
trajectory = Trajectory(data=data)

In [29]:
trajectory.sample(timestamps=[1.005]).data

{'time': array([1.005]), 'position': array([[1.005, 1.005]])}

In [30]:
trajectory.sample(timestamps=[-1, 0, 10, 11]).data  # sampling outside trajectory interval extrapolates with first and last value as constants

{'time': array([-1,  0, 10, 11]),
 'position': array([[1., 1.],
        [1., 1.],
        [4., 4.],
        [4., 4.]])}

In [31]:
type(trajectory.timestep), trajectory.timestep, trajectory.cfg.timestep  # timestep inferred as 1

(float, 1.0, None)

In [32]:
cfg = Trajectory().cfg

In [33]:
cfg.trajectory_keys = ("position", "time", "identity")

In [34]:
data = {
    "position": np.array([[1, 1], [2, 2], [4, 4]]).astype(float),
    "time": np.array([1, 2, 4]).astype(int),
    "identity": np.array(["a", "a", "a"], dtype=np.dtypes.StringDType)
}
trajectory = Trajectory(data=data)

type(trajectory.timestep), trajectory.timestep, trajectory.cfg.timestep  # timestep inferred as 1

(int, 1, None)

In [35]:
trajectory[trajectory.cfg.key_identity]

array(['a', 'a', 'a'], dtype=StringDType())

In [36]:
trajectory.interpolate().data["time"].dtype, trajectory.interpolate().data["identity"].dtype

(dtype('float64'), StringDType())

In [37]:
trajectory.interpolate(timestep=0.1).data

{'identity': array(['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a',
        'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a',
        'a', 'a', 'a', 'a', 'a'], dtype=StringDType()),
 'time': array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
        2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
        3.6, 3.7, 3.8, 3.9, 4. ]),
 'position': array([[1. , 1. ],
        [1.1, 1.1],
        [1.2, 1.2],
        [1.3, 1.3],
        [1.4, 1.4],
        [1.5, 1.5],
        [1.6, 1.6],
        [1.7, 1.7],
        [1.8, 1.8],
        [1.9, 1.9],
        [2. , 2. ],
        [2.1, 2.1],
        [2.2, 2.2],
        [2.3, 2.3],
        [2.4, 2.4],
        [2.5, 2.5],
        [2.6, 2.6],
        [2.7, 2.7],
        [2.8, 2.8],
        [2.9, 2.9],
        [3. , 3. ],
        [3.1, 3.1],
        [3.2, 3.2],
        [3.3, 3.3],
        [3.4, 3.4],
        [3.5, 3.5],
        [3.6, 3.6],
        [3.7, 3.7],
        [3.8, 3.8],
     

In [38]:
trajectory_interpolated = trajectory.interpolate(timestep=0.1)
trajectory_interpolated.timestep

0.1

In [39]:
trajectory_interpolated[::10, ("time", "position")]

{'time': array([1., 2., 3., 4.]),
 'position': array([[1., 1.],
        [2., 2.],
        [3., 3.],
        [4., 4.]])}

In [40]:
trajectory_interpolated[0, "time"] = -5

In [41]:
trajectory_interpolated.interpolate().timestamps

array([-5. , -4.9, -4.8, -4.7, -4.6, -4.5, -4.4, -4.3, -4.2, -4.1, -4. ,
       -3.9, -3.8, -3.7, -3.6, -3.5, -3.4, -3.3, -3.2, -3.1, -3. , -2.9,
       -2.8, -2.7, -2.6, -2.5, -2.4, -2.3, -2.2, -2.1, -2. , -1.9, -1.8,
       -1.7, -1.6, -1.5, -1.4, -1.3, -1.2, -1.1, -1. , -0.9, -0.8, -0.7,
       -0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,
        0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,  1.2,  1.3,  1.4,  1.5,
        1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,  2.3,  2.4,  2.5,  2.6,
        2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,  3.4,  3.5,  3.6,  3.7,
        3.8,  3.9,  4. ])

In [42]:
trajectory_interpolated.slice_window(-4, -3).timestamps

array([-4. , -3.9, -3.8, -3.7, -3.6, -3.5, -3.4, -3.3, -3.2, -3.1, -3. ])

In [43]:
trajectory_interpolated.slice_window(-4, -3, interpolate=False).timestamps

array([], dtype=float64)

In [44]:
trajectory_interpolated.timestamps

array([-5. ,  1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,
        2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,
        3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ])

In [45]:
data = {
    "position": np.array([[1, 1], [2, 2], [4, 4]]).astype(float),
    "time": np.array([1, 2, 4]),
    "identity": np.array(["a", "a", "b"], dtype=np.dtypes.StringDType)
}
data["position"] = np.repeat(data["position"], 2).reshape(-1, 2)
data["time"] = np.repeat(data["time"], 2)
data["time"][-1] = 5
data["identity"] = np.repeat(data["identity"], 2)
instances = InstanceCollection(data=data)

In [46]:
instances.select(timestamp=-1).data

{'identity': array([], dtype=StringDType()),
 'time': array([], dtype=int64),
 'position': array([], shape=(0, 2), dtype=float64)}

In [47]:
%timeit instances.select(timestamp=1)

75.7 μs ± 290 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [48]:
%timeit instances.select(timestamp=5, identity="b")

94.3 μs ± 223 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [50]:
TimestampedInstanceCollection(data=trajectory.interpolate().data).select(timestamp=3)

In [50]:
set([cfg, cfg.copy()])

TypeError: unhashable type: 'dict'

In [52]:
hash(dict())

TypeError: unhashable type: 'dict'